version: '3.2'

networks:
    neo4j:
        driver: bridge

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - neo4j
        environment:
            PHP_IDE_CONFIG: "serverName=neo4jogm"
            IDE_KEY: "NEO4JOGM"
            XDEBUG_CLIENT_PORT: "9009"
            XDEBUG_CLIENT_HOST: "172.17.0.1"
            XDEBUG_DISCOVER_CLIENT_HOST: 0
            XDEBUG_START_WITH_REQUEST: 1
            XDEBUG_MODE: "debug"
        stdin_open: true
        tty: true
        volumes:
            - .:/application
        depends_on:
            - neo4j
        extra_hosts:
            - "host.docker.internal:host-gateway"
        expose:
            - 9000
        container_name: neo4j-client
    neo4j:
        networks:
            - neo4j
        image: neo4j:3.5-enterprise
        healthcheck:
            test: [ "CMD", "neo4j status" ]
            interval: 30s
            timeout: 10s
            retries: 5
        expose:
            - 7474
            - 7687
        ports:
            - "7475:7474"
            - "7687:7687"
        environment:
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/test
            - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
        volumes:
            - ./tests/resources:/import
        container_name: neo4j-db
